# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpc < Formula
  desc "Google Play Console CLI — agent-friendly wrapper over the Android Publisher API v3"
  homepage "https://github.com/allen-hsu/gpc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/allen-hsu/gpc/releases/download/v0.1.0/gpc_0.1.0_darwin_amd64.tar.gz"
      sha256 "0ad1725a3ed9f9db4755f7d699b34c74ad962d66093a291eb801bc6059c31caf"

      define_method(:install) do
        bin.install "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/allen-hsu/gpc/releases/download/v0.1.0/gpc_0.1.0_darwin_arm64.tar.gz"
      sha256 "f167d1fc436ba452b3307ed988518a82a6b88176a778ab61af1e6cca7fedcd40"

      define_method(:install) do
        bin.install "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/allen-hsu/gpc/releases/download/v0.1.0/gpc_0.1.0_linux_amd64.tar.gz"
      sha256 "cba68ec8486116e5a5439033a51c82af814b5ed04c8db56c6e7a5ee29f972c2e"
      define_method(:install) do
        bin.install "gpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/allen-hsu/gpc/releases/download/v0.1.0/gpc_0.1.0_linux_arm64.tar.gz"
      sha256 "bfd7c056ea2f80ea07faee1a0bbd0938328df84fcad338f0b6cea42d453e3b9f"
      define_method(:install) do
        bin.install "gpc"
      end
    end
  end

  test do
    system "#{bin}/gpc --version"
  end
end
