# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpc < Formula
  desc "Google Play Console CLI — agent-friendly wrapper over the Android Publisher API v3"
  homepage "https://github.com/allen-hsu/gpc"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/allen-hsu/gpc/releases/download/v0.1.1/gpc_0.1.1_darwin_amd64.tar.gz"
      sha256 "9b7030152983ac43174762db22ff2c24783f4541116889397838c58296d00321"

      define_method(:install) do
        bin.install "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/allen-hsu/gpc/releases/download/v0.1.1/gpc_0.1.1_darwin_arm64.tar.gz"
      sha256 "e8746c8d330cf548a8056369b88c13084695e193cecefd941481fdfbcd7223a8"

      define_method(:install) do
        bin.install "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/allen-hsu/gpc/releases/download/v0.1.1/gpc_0.1.1_linux_amd64.tar.gz"
      sha256 "94ca7d1598192c36937a05cce2a9d32a8e5b2f04988e26f3d6ff51a8ef604fe7"
      define_method(:install) do
        bin.install "gpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/allen-hsu/gpc/releases/download/v0.1.1/gpc_0.1.1_linux_arm64.tar.gz"
      sha256 "082f7fee67a81ac7ad33d002569baac08579c70cfc45f27d4dab3f2538a54673"
      define_method(:install) do
        bin.install "gpc"
      end
    end
  end

  test do
    system "#{bin}/gpc --version"
  end
end
